### ISSUE TITLE
cannot resolve fragment

### ISSUE THREAD

**Issue by end-user** [thymeleaf/thymeleafexamples-layouts#6]
After cloning, ran `mvn test tomcat7:run` - tests were successful, tomcat started.  Browsed to http://localhost:8080/ and get a 500 error:

```
500 returned for / with message Error resolving fragment: "~{'http://www.thymeleaf.org' :: section.description}": template or fragment could not be resolved (template: "home/homeNotSignedIn" - line 18, col 27)
```

**Comment by ultraq** [comment]
I was able to replicate this.  Seems the line of code trying to go to `http://www.thymeleaf.org` to demonstrate how it can include templates even from URLs, needs to be updated to `https://www.thymeleaf.org` now that we're hosting pages with https.  I'll fix this up right away, but you can get the code working by going to line 18 of `homeNotSignedIn.html` file and changing the `http` to `https`.
