### ISSUE TITLE
Garbage project and article not running or working

### ISSUE THREAD

**Issue by 7--** [thymeleaf/thymeleafexamples-layouts#9]
![Screenshot from 2019-07-28 17-25-23](https://user-images.githubusercontent.com/4725003/62013169-ddee4b80-b15c-11e9-9eb0-e9fed05f58e6.png)
What is this garbage why would you upload when it's not broken.

This article is all wrong. I tried it in my own project and the thymleaf framework is broken:
`Caused by: org.thymeleaf.exceptions.TemplateInputException: Error resolving template [fragments/footer], template might not exist or might not be accessible by any of the configured Template Resolvers (template: "greeting" - line 19, col 13)
`

```
<html  xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:th="http://www.thymeleaf.org" >
<head>
<link rel="stylesheet" th:href="@{global.css}" />
<link rel="stylesheet" th:href="@{coin-lend.css}" />

</head>

<body class="Site">

	</h1>
	<div class="Site-content">

		<div id="main">

			    <div th:replace="fragments/footer :: footer"></div>

		</div>
........


```

```
</head>
<body th:fragment="menu">
	<ul  id="nav">
		<li><a href="/"> Analysis</a></li>
		<li><a href="/steps">Getting Started</a></li>

	</ul>
</body>
</html>
```

![Screenshot from 2019-07-28 17-31-03](https://user-images.githubusercontent.com/4725003/62013223-8f8d7c80-b15d-11e9-90bf-7d9375790d77.png)
https://www.thymeleaf.org/doc/articles/layouts.html

**Comment by 7--** [comment]
I found your issue. No where do you specify that the fragments folder needs to be inside the templates folder. Please update the article immidietly explaining the correct file paths.

**Comment by 7--** [comment]
Your project still doesnt run. You'll have to fix that

**Comment by danielfernandez** [comment]
I'm glad you found the issue in your code. I'm closing this and locking the conversation due to your inacceptable language. Please keep from using this tone in Thymeleaf's support infrastructure in the future.
